### ISSUE TITLE
In slides #307 through #311, the JavaScript function is labeled 'eq'. It should be 'gt'.

### ISSUE THREAD

**Issue by shriprem** [glebec/lambda-talk#3]
I am referring to the PDF version of the slide deck. The affected page numbers are 307-311, and 313.
---
The lambda function on these 6 slides are all correctly labeled as 'GT'. But the equivalent JS version of the function below has the label 'eq' on all the 6 slides.

Not a biggie, though. Thanks for the very well-presented talk. Thanks!

**Comment by glebec** [comment]
@shriprem thanks for the notice, I'll take a look. Not sure if I can update decks on SpeakerDeck but if so I'll fix it.

**Comment by glebec** [comment]
Added an errata notice. Thanks again!
